set(__QT_DEPLOY_TARGET_MiniOSCore_FILE D:/project8th/MiniOS-Simulator/build_qt_mingw64/libMiniOSCore.a)
set(__QT_DEPLOY_TARGET_MiniOSCore_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_MiniOSSimulator_FILE D:/project8th/MiniOS-Simulator/build_qt_mingw64/bin/MiniOSSimulator.exe)
set(__QT_DEPLOY_TARGET_MiniOSSimulator_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_MiniOSSimulator_RUNTIME_DLLS C:/Qt/6.10.2/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.10.2/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.10.2/mingw_64/bin/Qt6Core.dll)
